### PR TITLE
Aosp rebase android-13.0.0_r4 on master branch

### PR DESCRIPTION
**Pull request by swaroopbalan**
Signed-off-by: swaroopb <swaroop.balan@intel.com>
Tracked-On: OAM-104023

### CODE REVIEW

**Review by shyjumon-n — APPROVED** [review]
LGTM

**Review by tanujtekriwal — APPROVED** [review]
LGTM

**Review by iViggyPrabhu — APPROVED** [review]
Looks Good.

**Comment by iViggyPrabhu** [comment]
Merged internally, /absp/builders/celadon-mergerequest/builds/2996

**Pull request merged**
